# Generated by Django 3.1 on 2020-10-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='measure',
            field=models.CharField(default='Kg', max_length=200),
        ),
    ]
