# Generated by Django 2.2.3 on 2019-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgapp', '0003_auto_20190703_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='month',
            field=models.CharField(choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr')], default='January', max_length=11),
        ),
    ]
