# Generated by Django 3.1 on 2020-08-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fgapp', '0007_auto_20200831_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='crop_id',
            new_name='crop',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='market_id',
            new_name='market',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='country_id',
            new_name='country',
        ),
    ]
